expected_sections_data = [
    ('A/B Testing', "https://the-internet.herokuapp.com/abtest"),
    ('Add/Remove Elements', "https://the-internet.herokuapp.com/add_remove_elements/"),
    ('Basic Auth (user and pass: admin)', "https://the-internet.herokuapp.com/basic_auth"),
    ('Broken Images', "https://the-internet.herokuapp.com/broken_images"),
    ('Challenging DOM', "https://the-internet.herokuapp.com/challenging_dom"),
    ('Checkboxes', "https://the-internet.herokuapp.com/checkboxes"),
    ('Context Menu', "https://the-internet.herokuapp.com/context_menu"),
    ('Digest Authentication (user and pass: admin)', "https://the-internet.herokuapp.com/digest_auth"),
    ('Disappearing Elements', "https://the-internet.herokuapp.com/disappearing_elements"),
    ('Drag and Drop', "https://the-internet.herokuapp.com/drag_and_drop"),
    ('Dropdown', "https://the-internet.herokuapp.com/dropdown"),
    ('Dynamic Content', "https://the-internet.herokuapp.com/dynamic_content"),
    ('Dynamic Controls', "https://the-internet.herokuapp.com/dynamic_controls"),
    ('Dynamic Loading', "https://the-internet.herokuapp.com/dynamic_loading"),
    ('Entry Ad', "https://the-internet.herokuapp.com/entry_ad"),
    ('Exit Intent', "https://the-internet.herokuapp.com/exit_intent"),
    ('File Download', "https://the-internet.herokuapp.com/download"),
    ('File Upload', "https://the-internet.herokuapp.com/upload"),
    ('Floating Menu', "https://the-internet.herokuapp.com/floating_menu"),
    ('Forgot Password', "https://the-internet.herokuapp.com/forgot_password"),
    ('Form Authentication', "https://the-internet.herokuapp.com/login"),
    ('Frames', "https://the-internet.herokuapp.com/frames"),
    ('Geolocation', "https://the-internet.herokuapp.com/geolocation"),
    ('Horizontal Slider', "https://the-internet.herokuapp.com/horizontal_slider"),
    ('Hovers', "https://the-internet.herokuapp.com/hovers"),
    ('Infinite Scroll', "https://the-internet.herokuapp.com/infinite_scroll"),
    ('Inputs', "https://the-internet.herokuapp.com/inputs"),
    ('JQuery UI Menus', "https://the-internet.herokuapp.com/jqueryui/menu"),
    ('JavaScript Alerts', "https://the-internet.herokuapp.com/javascript_alerts"),
    ('JavaScript onload event error', "https://the-internet.herokuapp.com/javascript_error"),
    ('Key Presses', "https://the-internet.herokuapp.com/key_presses"),
    ('Large & Deep DOM', "https://the-internet.herokuapp.com/large"),
    ('Multiple Windows', "https://the-internet.herokuapp.com/windows"),
    ('Nested Frames', "https://the-internet.herokuapp.com/nested_frames"),
    ('Notification Messages', "https://the-internet.herokuapp.com/notification_message"),
    ('Redirect Link', "https://the-internet.herokuapp.com/redirector"),
    ('Secure File Download', "https://the-internet.herokuapp.com/download_secure"),
    ('Shadow DOM', "https://the-internet.herokuapp.com/shadowdom"),
    ('Shifting Content', "https://the-internet.herokuapp.com/shifting_content"),
    ('Slow Resources', "https://the-internet.herokuapp.com/slow"),
    ('Sortable Data Tables', "https://the-internet.herokuapp.com/tables"),
    ('Status Codes', "https://the-internet.herokuapp.com/status_codes"),
    ('Typos', "https://the-internet.herokuapp.com/typos"),
    ('WYSIWYG Editor', "https://the-internet.herokuapp.com/tinymce"),
]

# expected_sections_links = [
#     "https://the-internet.herokuapp.com/abtest",
#     "https://the-internet.herokuapp.com/add_remove_elements/",
#     "https://the-internet.herokuapp.com/basic_auth",
#     "https://the-internet.herokuapp.com/broken_images",
#     "https://the-internet.herokuapp.com/challenging_dom",
#     "https://the-internet.herokuapp.com/checkboxes",
#     "https://the-internet.herokuapp.com/context_menu",
#     "https://the-internet.herokuapp.com/digest_auth",
#     "https://the-internet.herokuapp.com/disappearing_elements",
#     "https://the-internet.herokuapp.com/drag_and_drop",
#     "https://the-internet.herokuapp.com/dropdown",
#     "https://the-internet.herokuapp.com/dynamic_content",
#     "https://the-internet.herokuapp.com/dynamic_controls",
#     "https://the-internet.herokuapp.com/dynamic_loading",
#     "https://the-internet.herokuapp.com/entry_ad",
#     "https://the-internet.herokuapp.com/exit_intent",
#     "https://the-internet.herokuapp.com/download",
#     "https://the-internet.herokuapp.com/upload",
#     "https://the-internet.herokuapp.com/floating_menu",
#     "https://the-internet.herokuapp.com/forgot_password",
#     "https://the-internet.herokuapp.com/login",
#     "https://the-internet.herokuapp.com/frames",
#     "https://the-internet.herokuapp.com/geolocation",
#     "https://the-internet.herokuapp.com/horizontal_slider",
#     "https://the-internet.herokuapp.com/hovers",
#     "https://the-internet.herokuapp.com/infinite_scroll",
#     "https://the-internet.herokuapp.com/inputs",
#     "https://the-internet.herokuapp.com/jqueryui/menu",
#     "https://the-internet.herokuapp.com/javascript_alerts",
#     "https://the-internet.herokuapp.com/javascript_error",
#     "https://the-internet.herokuapp.com/key_presses",
#     "https://the-internet.herokuapp.com/large",
#     "https://the-internet.herokuapp.com/windows",
#     "https://the-internet.herokuapp.com/nested_frames",
#     "https://the-internet.herokuapp.com/notification_message",
#     "https://the-internet.herokuapp.com/redirector",
#     "https://the-internet.herokuapp.com/download_secure",
#     "https://the-internet.herokuapp.com/shadowdom",
#     "https://the-internet.herokuapp.com/shifting_content",
#     "https://the-internet.herokuapp.com/slow",
#     "https://the-internet.herokuapp.com/tables",
#     "https://the-internet.herokuapp.com/status_codes",
#     "https://the-internet.herokuapp.com/typos",
#     "https://the-internet.herokuapp.com/tinymce",
# ]
